### ISSUE TITLE
Can you guys create a colab/gradiodemo? 

### ISSUE THREAD

**Issue by LucasSilvaFerreira** [ShuhongChen/panic3d-anime-reconstruction#1]
It would be amazing! Nice job

**Comment by zeng-yifei** [comment]
Oh, I think it will be very hard to build a colab demo. It took me really a while to build it locally. TvT. Hope that someone can build it one day.

**Comment by ShuhongChen** [comment]
Thanks for the kind words, though I'm not very happy with the quality personally

It's tricky to build a colab demo since any new image needs [segm](https://github.com/ShuhongChen/bizarre-pose-estimator#character-background-segmentation) + [face keypoints](https://github.com/hysts/anime-face-detector) (calculated from two other repos, with different dependcies); if we have time we might give it a shot
