### ISSUE TITLE
Error: Exception: (standalone) XOpenDisplay: cannot open display

### ISSUE THREAD

**Issue by LiRunyi2001** [ShuhongChen/panic3d-anime-reconstruction#14]
Hi there! I am trying to running script `python3 -m _scripts.render_all_animerecon_daredemoE`, however it failed with error information:
![image](https://user-images.githubusercontent.com/54633216/231655465-3833b0af-3f76-46aa-9217-fdf88a266f2a.png)
Same error also occured in rendering `ortho`, `ortho_xyz`, `rgb60`. 
Is there any solution for this error? Thanks!

**Comment by ShuhongChen** [comment]
Are you running headlessly (like on a cluster), or on a non-linux machine?  I believe in order to create a context, there needs an X server running in the background

You might be able to use xvfb, which creates a virtual X server environment.  Xvfb should already in the docker image; if I remember correctly, this is how I got to render on a cluster.  Maybe you can try to change the [render command](https://github.com/ShuhongChen/vroid_renderer/blob/ea0891e422e3c9a236c5ecd1335c5ea504b575ea/_scripts/render_all_animerecon_daredemoE.py#L29) to:

```
f'xvfb-run python3 -m _scripts.render_{dtype}',
```

**Comment by LiRunyi2001** [comment]
Thank you! I'll try this later.

**Comment by LiRunyi2001** [comment]
Hi, there! Thanks for your previous advise, however some new errors happened:
(I am running in the docker environment provided in this repo)
(1) After I changed the command with xvfb, the rendering process of `ortho_xyza` and `xyza60`
 still failed with "Exception: (standalone) XOpenDisplay: cannot open display".
![image](https://user-images.githubusercontent.com/54633216/232281569-5e816db0-310c-4b9a-a93d-0547b23b34dd.png)
![failure](https://user-images.githubusercontent.com/54633216/232282707-ca87c47a-4131-4232-a28d-c00dcb60a7c3.png)
(2) For rendering `ortho` and `rgb60`, the error information is:
![image](https://user-images.githubusercontent.com/54633216/232283146-bfcc88ce-62d5-482b-af36-17a9bb1fca39.png)
I checked the repos you've provided, but it seems that I cannot find such directory or file.

Besides, I noticed that to run script `python3 -m _scripts.eval.generate && python3 -m _scripts.eval.measure`, these files should also be prepared:
![image](https://user-images.githubusercontent.com/54633216/232283392-da9a9bdc-0f17-45f1-a41a-e4fc415d090f.png)
while I cannot find these files. Will these be generated after rendering process?

Is there any solution for this issue? Thanks!

**Comment by ShuhongChen** [comment]
> (1) After I changed the command with xvfb, the rendering process of ortho_xyza and xyza60 still failed with "Exception: (standalone) XOpenDisplay: cannot open display".

Maybe xvfb doesn't have enough time to restart an instance; you can try adding `time.sleep(10)` after each `os.system` call?

> (2) For rendering ortho and rgb60, the error information is: I checked the repos you've provided, but it seems that I cannot find such directory or file.

The file is [here](https://github.com/ShuhongChen/vroid_renderer/blob/ea0891e422e3c9a236c5ecd1335c5ea504b575ea/_cells/shaders/rutileE.glsl).  I'm not sure how you're rendering from `panic3d-anime-reconstruction`; you need to run the render scripts from the `vroid_renderer` repo where they come from, you cannot merge different repos together

> while I cannot find these files. Will these be generated after rendering process?

Not all of these are required; if it doesn't exist the code should still continue because of the [if statement](https://github.com/ShuhongChen/panic3d-anime-reconstruction/blob/f0b18007c3c55f7a1a2d186f950f157924ce1cd7/_databacks/lustrous_renders_v1.py#L130)

**Comment by LiRunyi2001** [comment]
Thanks! The rendering process worked well, however `python3 -m _scripts.eval.generate && python3 -m _scripts.eval.measure` still cannot work. 
To run generate script, in this line:
![image](https://user-images.githubusercontent.com/54633216/232368857-00d8534d-fddd-4ce4-973a-fe7a07711852.png)
it will call `lustrous_renders_v1.py`, in this line:
![image](https://user-images.githubusercontent.com/54633216/232369095-824fefc2-fc59-4d41-968e-5eaa39a1b521.png)
However, as I've mentioned in former comment, I do not have these json files, so `self.rp_meta` remains an empty dict.  Thus in this line it will throw an key error: 
![image](https://user-images.githubusercontent.com/54633216/232369574-584d6330-2258-44ef-bfd3-df034ad3be71.png)
Very grateful for any solution that you could provide :)

**Comment by ShuhongChen** [comment]
Sorry about that, I didn't realize none of the jsons were included; the important ones should be `rutileE_meta.json` and `daredemoE_meta.json`

I've put them in the new zip in the [drive folder](https://drive.google.com/drive/folders/1Zpt9x_OlGALi-o-TdvBPzUPcvTc7zpuV?usp=sharing)
