### ISSUE TITLE
how to run this project on Google Colab

### ISSUE THREAD

**Issue by littlewhitesea** [ShuhongChen/panic3d-anime-reconstruction#32]
Thanks for your great work.

I am not very familiar with docker. I would like to know whether I can run this project normally on Google Colab, since it is indicated that this project requires docker with a GPU. However, current Google Colab doesn't support docker.

Looking forward to your reply.

**Comment by ShuhongChen** [comment]
Hi, thanks for your interest in our project; unfortunately it's admittedly a bit hard to get this running in colab, since you'd need to install all dependencies from `_env/Dockerfile` into the colab session, in addition to downloading/linking the data to the right place in the VM

My recommendation would still be to try out docker on a local gpu machine; docker's a very good tool to use
